version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: zaeus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zaeus_db
      POSTGRES_USER: zaeus_user
      POSTGRES_PASSWORD: zaeus_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - zaeus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zaeus_user -d zaeus_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: zaeus-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zaeus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: redis-server --appendonly yes --requirepass redis_password

  # PgAdmin (Optional - pentru development)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zaeus-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zaeus.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - zaeus-network
    depends_on:
      - postgres

  # Redis Commander (Optional - pentru development)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: zaeus-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: redis:redis:6379:0:redis_password
    ports:
      - "8081:8081"
    networks:
      - zaeus-network
    depends_on:
      - redis

volumes:
  postgres_data:
    name: zaeus_postgres_data
  redis_data:
    name: zaeus_redis_data
  pgadmin_data:
    name: zaeus_pgadmin_data

networks:
  zaeus-network:
    name: zaeus-network
    driver: bridge